### ISSUE TITLE
HL7各版本应用现状

### ISSUE THREAD

**Issue by songchao168** [wanghaisheng/hit-best-practices#2]
你好。
 抱歉现在才把问题提交。
由于公司项目的需要 我最近在看HL7，之前毫无HL7相关的经验。现在在对HL7的版本选择上不是很明确。公司项目大概业务是记录和管理个人健康信息， 涉及到的业务数据大概有 体格检查，表型    环境，基因组学，转录组学，代谢组学等。下面是我的问题。
1 请问HL7各版本目前在国内外的应用现状是什么？
2 目前HIS厂商在使用HL7更倾向于哪个版本(基于什么样的原因)？
3 HL7 v3是否是一套成熟的标准，是否推荐在实际项目中使用。

**Comment by wanghaisheng** [comment]
1.HL7是一系列的标准  包含了数据交换 临床文档 决策支持等内容
数据交换这边主要是HL7V.X系列的标准和HL7V3 目前在国内多用的是V2.X，然而卫计委所推的相关标准则采用的是HL7V3消息
临床文档这边卫计委也选择了CDA文档规范，我们称之为共享文档规范 用来约束电子病历、健康档案的相关内容
上述的应用具体可参考目前已经通过卫计委互联互通标准符合性测试的相关机构
2.HIT厂商产品内部大多未直接采用任何HL7标准或其他任何标准，更多的做法是在外面嵌套一层用于不同协议格式的转换，这也是符合现实情况的 
3.如果你指的是HL7 V3消息的话 个人不建议使用 因为国际上来看  使用的项目大多没有取得很好的成果 而且成本巨高无比 且标准的社区不活跃
4.组学的数据我不甚了解 但关注了如下的项目 供参考  你所提到的业务数据大多停留在健康档案的范畴 可直接使用卫计委的共享文档规范或在其基础上进行改造，亦或直接采用FHIR标准来表达此类数据
https://github.com/bigdatagenomics
http://projects.iq.harvard.edu/smartgenomics/motivation-and-description
http://www.slideserve.com/astin/clinical-genomics-hl7-sig
http://hl7-fhir.github.io/

**Comment by songchao168** [comment]
@wanghaisheng  非常感谢你提供的资料。
